version: '3.4'

services:
  com3014imagetagging:
    image: com3014imagetagging
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python -u app.py
    ports:
      - 3303:3303
