version: '3.4'

services:
  com3014imagetagging:
    image: com3014imagetagging
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3303:3303
    networks:
      - com3014_image_storage_image-net
networks:
  com3014_image_storage_image-net:
    external: true
