version: '3.4'

services:
  com3014imagetagging:
    image: com3014imagetagging
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 3303"]
    ports:
      - 3303:3303
      - 5678:5678
    environment:
      - FLASK_APP=app.py
