name: Flask CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m unittest discover
    - name: Create artifact
      run: |
        zip -r app.zip app.py

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy code to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        source: app.zip
        target: /home/ubuntu/app.zip
    - name: Unzip code
      run: |
        ssh ubuntu@${{ secrets.SERVER_HOST }} -i ${{ secrets.SERVER_KEY }} 'cd /home/ubuntu && unzip -o app.zip'
    - name: Restart application
      run: |
        ssh ubuntu@${{ secrets.SERVER_HOST }} -i ${{ secrets.SERVER_KEY }} 'sudo systemctl restart app.service'
