name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker compose build

    - name: Run Unit Tests
      run: docker compose run com3014_image_tagging python3 -m pytest tests/

    - name: Make Test Request
      run: |
        docker compose up -d
        sleep 5
        curl -X POST localhost:5000/upload -F 'file=@/path/to/test_image.jpg'
        docker compose down

    - name: Trigger Main Workflow
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: com3014-group9/com3014_meowstagram
        token: ${{ secrets.PAT }}
        event-type: trigger-build
