name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t com3014_image_tagging .

    - name: Run Unit Tests
      run: docker run com3014_image_tagging python3 -m pytest

    - name: Make Test Request
      run: |
        docker run -d --name my_flask_app com3014_image_tagging
        sleep 5
        curl -X POST localhost:5000/upload
        docker stop my_flask_app

    - name: Trigger Main Workflow
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: com3014-group9/com3014_meowstagram
        token: ${{ secrets.PAT }}
        event-type: trigger-build
