name: CI Pipeline

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install PyTorch
      run: |
        python -m pip install torch torchvision
    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build Docker Image
      run: docker compose build
    - name: Run Unit Tests
      run: docker compose run imager-app python3 -m pytest
    - name: Trigger Main Workflow
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v2
      with:
        repository: com3014-group9/com3014_meowstagram
        token: ${{ secrets.PAT }}
        event-type: trigger-build
